image: registry.gitlab.com/alex4401/arkse-mobile-extraction
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - extract

before_script:
  - pip install -r requirements.txt
  - cd thirdparty/googleplayapi
  - python setup.py build
  - cd ../..
  - mkdir artifacts tmp
  - curl "https://gitlab.com/api/v4/projects/13304753/jobs/artifacts/master/raw/target/debug/uasset-data-extractor?job=build" --output "extractor"

extract-main:
  stage: extract
  tags:
    - shelled
  artifacts:
    paths:
      - "artifacts/*.txt"
      - "artifacts/json/"
      - "artifacts/json_dirty/"
  script:
    - python pull-blobs.py main
    - cd tmp
    - unzip ../main.*.blob "ShooterGame/Content/Paks/pakchunk0-Android.pak"
    - ../thirdparty/ue4build/Engine/Binaries/Linux/UnrealPak-Linux-Debug.bin "ShooterGame/Content/Paks/pakchunk0-Android.pak" -List > ../artifacts/chunk0-filelist.txt
    - bash ../clean-up-unrealpak-output.sh ../artifacts/chunk0-filelist.txt
    - ../thirdparty/ue4build/Engine/Binaries/Linux/UnrealPak-Linux-Debug.bin "ShooterGame/Content/Paks/pakchunk0-Android.pak" -Extract content
    - cd ..
    - python runner.py tmp/content "^(.*)\.uasset$" artifacts/json true
    - python runner.py tmp/content "^(.*)\.uasset$" artifacts/json_dirty false

extract-patch:
  stage: extract
  tags:
    - shelled
  artifacts:
    paths:
      - "artifacts/*.txt"
      - "artifacts/json/"
      - "artifacts/json_dinostats/"
  script:
    - python pull-blobs.py patch
    - cd tmp
    - unzip ../patch.*.blob "ShooterGame/Content/Paks/pakchunk1-Android.pak"
    - ../thirdparty/ue4build/Engine/Binaries/Linux/UnrealPak-Linux-Debug.bin "ShooterGame/Content/Paks/pakchunk1-Android.pak" -List > ../artifacts/chunk1-filelist.txt
    - bash ../clean-up-unrealpak-output.sh ../artifacts/chunk1-filelist.txt
    - ../thirdparty/ue4build/Engine/Binaries/Linux/UnrealPak-Linux-Debug.bin "ShooterGame/Content/Paks/pakchunk1-Android.pak" -Extract content
    - cd ..
    - python runner.py tmp/content "^(.*)\.uasset$" artifacts/json true
    - python runner.py tmp/content "^DinoCharacterStatusComponent(.*)\.uasset$" artifacts/json_dinostats false
