kind: pipeline
type: docker
name: Build Environment Image

platform:
  os: linux
  arch: arm

steps:
# Temporary until a registry is set up.
- name: Build on host
  image: docker:latest
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  commands:
  - cd docker
  - docker build --tag "arksem/build-environment" -f Dockerfile .

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: Data Extraction
depends_on:
- Build Environment Image

platform:
  os: linux
  arch: arm

steps:
- name: Download tools
  image: arksem/build-environment
  environment:
    UDE_VERSION: 2.4.3.1
  commands:
  - bash download-extractor.sh "/job_shared/"
  volumes:
    - name: shared
      path: /job_shared

volumes:
- name: shared
  temp: {}