kind: pipeline
type: docker
name: Build Environment Image

platform:
  os: linux
  arch: arm

steps:
# Temporary until a registry is set up.
- name: build on host
  image: docker:latest
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  commands:
  - cd docker
  - docker build --tag "arksem/build-environment" -f Dockerfile .

#---
#
#kind: pipeline
#type: docker
#name: Data Extraction
#
#platform:
#  os: linux
#  arch: arm
#
#steps:
#- name: 
#  image: python:3.5.8-slim-stretch
#  commands:
#  - echo Hello world!