kind: pipeline
type: docker
name: Build Environment Image

platform:
  os: linux
  arch: arm

steps:
# Temporary until a registry is set up.
- name: Build on host
  image: docker:latest
  environment:
    DOCKER_REGISTRY_USER_NAME:
      from_secret: DOCKER_REGISTRY_USER_NAME
    DOCKER_REGISTRY_TOKEN:
      from_secret: DOCKER_REGISTRY_TOKEN

  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
    
  commands:
  - cd docker
  - docker build --tag "docker.pkg.github.com/alex4401/arksem-extraction-pipeline/build-environment" -f Dockerfile .
  - echo $DOCKER_REGISTRY_TOKEN | docker login docker.pkg.github.com --username $DOCKER_REGISTRY_USER_NAME --password-stdin
  - docker push docker.pkg.github.com/alex4401/arksem-extraction-pipeline/build-environment

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: Data Extraction
depends_on:
- Build Environment Image

platform:
  os: linux
  arch: arm

steps:
- name: Download tools
  image: docker.pkg.github.com/alex4401/arksem-extraction-pipeline/build-environment
  pull: if-not-exists
  environment:
    UDE_VERSION: 2.4.3.1
  commands:
  - bash download-extractor.sh "/job_shared/"
  volumes:
    - name: shared
      path: /job_shared

volumes:
- name: shared
  temp: {}
