name: Mobile ARK data extraction

on:
  check_suite:
    types: [ rerequested, requested ]
  issues:
    types: [ opened ]
  push:
    #branches:    
    #- live
  #schedule:
  #  - cron:  '0 * * * *'

jobs:
  run:
    runs-on: self-hosted
    env:
      gpAppPackageName: com.studiowildcard.wardrumstudios.ark
      EXTRACTOR_BRANCH: master

    steps:
    - uses: actions/checkout@v1
    - name: Initialize submodules
      run: git submodule update --init thirdparty/upakpy

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install GPAPI library
      run: |
        bash ci_scripts/install-libgpapi.sh /caches/arksem
        bash ci_scripts/link-cache.sh

    # Extractor setup
    - name: Download a build of the extractor
      run: bash ci_scripts/download-extractor.sh /caches/arksem/
    # Actual extraction
    #- name: Pull version data from Google Play
    #  env: # Or as an environment variable
    #    gsfDeviceId: ${{ secrets.GsfFakeDeviceId }}
    #    gsfDeviceCodename: ${{ secrets.GsfFakeDeviceType }}
    #    gsfAuthToken: ${{ secrets.GsfAuthToken }}
    #  run: |
    #    python gptool/pull-version-info.py
