name: Mobile ARK data extraction

on:
  check_suite:
    types: [ rerequested, requested ]
  issues:
    types: [ opened ]
  push:
    #branches:    
    #- live
  schedule:
    - cron:  '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      gpAppPackageName: com.studiowildcard.wardrumstudios.ark
      EXTRACTOR_BRANCH: master

    steps:
    - uses: actions/checkout@v1
    - name: Initialize submodules
      run: git submodule update --init --recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --system
        cd thirdparty/googleplayapi
        python setup.py build
        cd ../..
    - name: Download an extractor binary
      run: |
        bash download-extractor.sh $EXTRACTOR_BRANCH ude.bin
        chmod +x ude.bin
    - name: Pull version data from Google Play
      env: # Or as an environment variable
        gsfDeviceId: ${{ secrets.GsfFakeDeviceId }}
        gsfDeviceCodename: ${{ secrets.GsfFakeDeviceType }}
        gsfAuthToken: ${{ secrets.GsfAuthToken }}
      run: |
        python gptool/pull-version-info.py